//FETCH__REDUCER
export const FETCH = 'FETCH';
export const SLICE_TEMP = 'SLICE_TEMP';
export const SLICE_PRESSURE = 'SLICE_PRESSURE';
export const LOADING = 'LOADING';

//DATA__REDUCER
export const CHANGE__CHART = 'CHANGE__CHART';
export const CHANGE__SELECTED__TEMP = 'CHANGE__SELECT__TEMP';
export const CHANGE__SELECTED__PRESSURE = 'CHANGE__SELECT__PRESSURE';
export const CHANGE__OPEN__TEMP = 'CHANGE__OPEN__TEMP';
export const CHANGE__OPEN__PRESSURE = 'CHANGE__OPEN__PRESSURE';

//HEADER__REDUCER
export const CHANGE__CITY = 'CHANGE__CITY';
export const CHANGE__LANGUAGE = 'CHANGE__LANGUAGE';
export const OPEN__LANGUAGE = 'OPEN__LANGUAGE';
export const CHANGE__INPUT = 'CHANGE__INPUT';
